data <- read.table("C:/Users/Lefei/Downloads/exdata-data-household_power_consumption/
                   household_power_consumption.txt",sep=";",header=TRUE)
firstDate<-as.Date("2007-02-01","%Y-%m-%d")
secondDate<-as.Date("2007-02-02","%Y-%m-%d")
data[,1]<-as.Date(data[,1],"%d/%m/%Y")
d<-subset(data,Date==firstDate|Date==secondDate)

d[,3]<-as.numeric(as.character(d[,3]))
d[,"Sub_metering_1"]<-as.numeric(as.character(d[,"Sub_metering_1"]))
d[,"Sub_metering_2"]<-as.numeric(as.character(d[,"Sub_metering_2"]))
d[,"Sub_metering_3"]<-as.numeric(as.character(d[,"Sub_metering_3"]))
d[,"Voltage"]<-as.numeric(as.character(d[,"Voltage"]))
d[,4]<-as.numeric(as.character(d[,4]))

dq<-paste(as.character(d[,1]),as.character(d[,2]),sep=" ")
sdq<-strptime(dq,"%Y-%m-%d %H:%M:%S")
png(filename = "plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
plot(sdq,d[,3],type="l",ylab="Global Active Power (Kilowatts)",xlab="")
plot(sdq,d[,"Voltage"],type="l",ylab="Voltage",xlab="datetime")
plot(sdq,d[,"Sub_metering_1"],type="l",ylab="Energy sub metering",xlab="")
lines(sdq,d[,"Sub_metering_2"],col="red")
lines(sdq,d[,"Sub_metering_3"],col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1, col=c('black', 'red', 'blue'),cex=0.5)
plot(sdq,d[,4],type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()